name: Autopep8 Code Check

on: [push, pull_request]

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.10'
      - name: Install dependencies
        run: |
          pip install autopep8
      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive .
