name: Flakes Code Check

on: [push, pull_request]

jobs:
  flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.10'

      - name: Install dependencies
        run: |
          pip install pyflakes

      - name: Run Pyflakes
        run: pyflakes hw2/*.py